version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: auto-ex
    environment:
      MYSQL_ROOT_PASSWORD: ${DATA_BASE_PASSWORD_DEVELOPMENT}
      MYSQL_DATABASE: ${DATA_BASE_NAME_DEVELOPMENT}
      MYSQL_USER: ${DATA_BASE_USERNAME_DEVELOPMENT}
      MYSQL_PASSWORD: ${DATA_BASE_PASSWORD_DEVELOPMENT}
    ports:
      - "${DATA_BASE_PORT_DEVELOPMENT}:${DATA_BASE_PORT_DEVELOPMENT}"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
