version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: auto-ex
    environment:
      MYSQL_ROOT_PASSWORD: ${DATA_BASE_PASSWORD}
      MYSQL_DATABASE: ${DATA_BASE_NAME}
      MYSQL_USER: ${DATA_BASE_USERNAME}
      MYSQL_PASSWORD: ${DATA_BASE_PASSWORD}
    ports:
      - "${DATA_BASE_PORT}:${DATA_BASE_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
